package org.jax.octvolavg;

import java.awt.Rectangle;
import java.io.InputStream;
import java.util.Scanner;

import javax.swing.SwingUtilities;

public class LicenseDialog extends javax.swing.JDialog
{
    private static final long serialVersionUID = 8343233758498428253L;
    
    public LicenseDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        this.initComponents();
        
        InputStream aboutStream = this.getClass().getResourceAsStream("about.txt");
        this.aboutTextArea.setText(streamToString(aboutStream));
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                LicenseDialog.this.aboutTextArea.scrollRectToVisible(new Rectangle(0, 0, 1, 1));
            }
        });

        InputStream licenseStream = this.getClass().getResourceAsStream("license.txt");
        this.licenseTextArea.setText(streamToString(licenseStream));
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                LicenseDialog.this.licenseTextArea.scrollRectToVisible(new Rectangle(0, 0, 1, 1));
            }
        });

        InputStream ccLicenseStream = this.getClass().getResourceAsStream("cc-4.0.txt");
        this.ccLicenseTextArea.setText(streamToString(ccLicenseStream));
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                LicenseDialog.this.ccLicenseTextArea.scrollRectToVisible(new Rectangle(0, 0, 1, 1));
            }
        });
    }
    
    private static String streamToString(InputStream is) {
        Scanner s = new Scanner(is).useDelimiter("\\A");
        return s.hasNext() ? s.next() : "";
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel bottomPanel = new javax.swing.JPanel();
        javax.swing.JButton okButton = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        aboutScrollPane = new javax.swing.JScrollPane();
        aboutTextArea = new javax.swing.JTextArea();
        licenseScrollPane = new javax.swing.JScrollPane();
        licenseTextArea = new javax.swing.JTextArea();
        ccLicenseScrollPane = new javax.swing.JScrollPane();
        ccLicenseTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About and License");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(okButton);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        aboutScrollPane.setPreferredSize(new java.awt.Dimension(600, 400));

        aboutTextArea.setEditable(false);
        aboutTextArea.setColumns(20);
        aboutTextArea.setLineWrap(true);
        aboutTextArea.setRows(5);
        aboutTextArea.setWrapStyleWord(true);
        aboutScrollPane.setViewportView(aboutTextArea);

        tabbedPane.addTab("About", aboutScrollPane);

        licenseScrollPane.setPreferredSize(new java.awt.Dimension(600, 400));

        licenseTextArea.setEditable(false);
        licenseTextArea.setColumns(20);
        licenseTextArea.setRows(5);
        licenseScrollPane.setViewportView(licenseTextArea);

        tabbedPane.addTab("License", licenseScrollPane);

        ccLicenseTextArea.setColumns(20);
        ccLicenseTextArea.setRows(5);
        ccLicenseScrollPane.setViewportView(ccLicenseTextArea);

        tabbedPane.addTab("CC Attribution-NoDerivatives 4.0 International License", ccLicenseScrollPane);

        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane aboutScrollPane;
    private javax.swing.JTextArea aboutTextArea;
    private javax.swing.JScrollPane ccLicenseScrollPane;
    private javax.swing.JTextArea ccLicenseTextArea;
    private javax.swing.JScrollPane licenseScrollPane;
    private javax.swing.JTextArea licenseTextArea;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

}
